WebApp/Models/ErrorViewModel.cs
namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Models/Log.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models;

public class Log
{
    [Key]
    public int Id { get; set; }
    [Required]
    public int Code { get; set; }
    [Required]
    public DateTime CheckInTime { get; set; }
    [Required]
    public DateTime CheckOutTime { get; set; }
    [Required]
    public double Price { get; set; }

    public int? SubscriptionId { get; set; }
    public Subscription? Subscription { get; set; }
}

WebApp/Models/ParkingSpot.cs
namespace WebApp.Models;

public class ParkingSpots
{
    public int TotalSpots { get; set; }
    public int ReservedSpots { get; set; }
    public int RegularSpots { get; set; }
}

WebApp/Models/PricingPlan.cs
namespace WebApp.Models;

public class PricingPlan
{
    public int Id { get; set; }
    public double HourlyPricing { get; set; }
    public double DailyPricing { get; set; }
    public int MinimumHours { get; set; }
    public int PricingPlanTypeId { get; set; }
    public PricingPlanType Type { get; set; }
}

WebApp/Models/PricingPlanType.cs
namespace WebApp.Models;

public class PricingPlanType
{
    public int Id { get; set; }
    public string Name { get; set; }
}
    

WebApp/Models/Subscription.cs
namespace WebApp.Models
{
    public class Subscription
    {
        public int Id { get; set; }
        public int Code { get; set; }
        public double Price { get; set; }
        public double DiscountValue { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public bool IsDeleted { get; set; }
    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/LogController.cs
using AutoMapper;
using Domain.Repositories;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
	public class LogController : Controller
	{
		private readonly IEfLogRepository _logRepository;
		private readonly IMapper _mapper;

		public LogController(IEfLogRepository logRepository, IMapper mapper)
		{
			_logRepository = logRepository;
			_mapper = mapper;
		}
		public IActionResult ListAll()
		{
			var logs = _logRepository.GetAllLogs();
			return View(_mapper.Map<IEnumerable<Log>>(logs));
		}
		[HttpPost]
		public IActionResult ListAll(Log log)
		{
			var newLog = log;
			_logRepository.CreateLog(_mapper.Map<Domain.Entities.Log>(log));
			return RedirectToAction("ListAll");
		}
	}
}

WebApp/Controllers/PricingPlanController.cs
using AutoMapper;
using Domain.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers;

public class PricingPlanController : Controller
{
    private readonly IPricingPlanRepository pricingPlanRepository;
    private readonly IMapper mapper;

    public PricingPlanController(IPricingPlanRepository pricingPlanRepository, IMapper mapper)
    {
        this.pricingPlanRepository = pricingPlanRepository;
        this.mapper = mapper;
    }
    public IActionResult PricingPlanList()
    {
        return View(mapper.Map<IEnumerable<Models.PricingPlan>>(pricingPlanRepository.GetPricingPlans()));
    }

    public IActionResult EditPricingPlan(int id)
    {
        return View(mapper.Map<Models.PricingPlan>(pricingPlanRepository.GetPricingPlanById(id)));
    }

    [HttpPost]
    public IActionResult EditPricingPlan(Models.PricingPlan pricingPlan)
    {
        pricingPlanRepository.UpdatePricingPlan(mapper.Map<Domain.Entities.PricingPlan>(pricingPlan));

        return View("PricingPlanList", mapper.Map<IEnumerable<Models.PricingPlan>>(pricingPlanRepository.GetPricingPlans()));
    }
}

WebApp/Controllers/SpotListingController.cs
using AutoMapper;
using Domain.Data;
using Domain.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class SpotListingController : Controller
    {
        private readonly IParkingRepository _parkingContext;
        private readonly ISubscriptionRepository _subscriptionRepository;
        private readonly IMapper _mapper;

        public SpotListingController(IParkingRepository parkingContext, ISubscriptionRepository subsctriptionContext, IMapper mapper)
		{
            _parkingContext = parkingContext;
            _subscriptionRepository = subsctriptionContext;
            _mapper = mapper;
		}
        public IActionResult Total()
        {
            var all = _parkingContext.GetParkingSpots().TotalSpots;
            var reserved = _subscriptionRepository.GetAllSubscriptions().Count();
            var parkingSpots = new ParkingSpots() 
            { 
                TotalSpots = all,
                ReservedSpots = reserved,
                RegularSpots = all - reserved
            };
            return View(parkingSpots);
        }

        [HttpPost]
        public IActionResult Total(ParkingSpots parkingSpots)
        {
            var newParkingSpots = new ParkingSpots()
            {
                TotalSpots = parkingSpots.TotalSpots,
                ReservedSpots = parkingSpots.ReservedSpots,
                RegularSpots = parkingSpots.TotalSpots - parkingSpots.ReservedSpots
            };
            _parkingContext.UpdateParkingSpots(parkingSpots.TotalSpots);
            return View(newParkingSpots);
        }
    }
}

WebApp/Controllers/SubscriptionController.cs
using AutoMapper;
using Domain.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class SubscriptionController : Controller
    {
        private readonly ISubscriptionRepository _subscriptionRepository;
        private readonly IMapper _mapper;

        public SubscriptionController(ISubscriptionRepository subscriptionRepository, IMapper mapper)
        {
            _subscriptionRepository = subscriptionRepository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ListAll()
        {
            var result = _subscriptionRepository.GetAllSubscriptions();
            var subscriptions = _mapper.Map<IEnumerable<Subscription>>(result);

            return View("SubscriptionsList", subscriptions);
        }

        public IActionResult AddSubscription()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddSubscription(Subscription subscription)
        {
            var subscriptionToAdd = _mapper.Map<Domain.Entities.Subscription>(subscription);
            _subscriptionRepository.AddSubscription(subscriptionToAdd);

            return RedirectToAction("ListAll", "SubscriptionsList");
        }

        public IActionResult ViewSubscriptionDetails(int id)
        {
            var subscriptionDetails = _subscriptionRepository.GetAllSubscriptions()
                .FirstOrDefault(p => p.Id == id);

            if (subscriptionDetails == null)
            {
                return NotFound();
            }

            return View("SubscriptionDetails", _mapper.Map<WebApp.Models.Subscription>(subscriptionDetails));
        }

        public IActionResult DeleteSubscription(int id)
        {
           _subscriptionRepository.DeleteSubscription(id);

            return RedirectToAction("ListAll");
        }
    }
}

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApp/Views/Log/ListAll.cshtml
@model IEnumerable<Log>

@{
	ViewBag.Title = "List Of Logs";
}
<h2>Add Log</h2>
<form asp-controller="Log" asp-action="ListAll" method="post">
    <label for="Code">Code</label>
    <input type="text" id="Code" name="Code" class="form-control" required />
    <br />
	<label for="CheckInTime">CheckInTime</label>
    <input type="date" id="CheckInTime" name="CheckInTime" class="form-control" required />
    <br />
	<label for="CheckOutTime">CheckOutTime</label>
    <input type="date" id="CheckOutTime" name="CheckOutTime" class="form-control" required />
    <br />
    <label for="Price">Price</label>
    <input type="text" id="Price" name="Price" class="form-control" required />
    <br />
    <button type="submit" class="btn btn-primary">Add Log</button>
    <br />
    <br />
</form>

<h2>List Of All Logs</h2>
<br />
<ul class="list-group">
	@foreach (var item in @Model)
	{
		<li class="list-group-item">Price: @item.Price CheckInTime: @item.CheckInTime CheckOutTime: @item.CheckOutTime</li>
	}
</ul>

WebApp/Views/PricingPlan/EditPricingPlan.cshtml
@model WebApp.Models.PricingPlan

@{
    ViewBag.Title = "Edit Pricing Plan";
}

<form asp-controller="PricingPlan" asp-action="EditPricingPlan" method="post">
    <input type="hidden" asp-for="@Model.Id" />
    <input type="hidden" asp-for="@Model.Type.Id" />
    <input type="hidden" asp-for="@Model.Type.Name" />

    <p>
        <label asp-for="@Model.HourlyPricing"></label>
        <input asp-for="@Model.HourlyPricing" value="@Model.HourlyPricing">
    </p>
    <p>
        <label asp-for="@Model.DailyPricing"></label>
        <input asp-for="@Model.DailyPricing" value="@Model.DailyPricing">
    </p>
    <p>
        <label asp-for="@Model.MinimumHours"></label>
        <input asp-for="@Model.MinimumHours" value="@Model.MinimumHours">
    </p>
    <button type="submit" class="btn btn-warning">Update</button>
</form>

WebApp/Views/PricingPlan/Index.cshtml
@model IEnumerable<WebApp.Models.PricingPlan>

@{
    ViewBag.Title = "List of Pricing Plans";
}

@foreach (var plan in Model)
{
    @plan.Type.Name.ToUpper()
    <a class="btn btn-primary"
       asp-controller="PricingPlan"
       asp-action="PricingPlanDetails"
       asp-route-id="@plan.Id">
        Details
    </a>
    <br />
}

WebApp/Views/PricingPlan/PricingPlanList.cshtml
@model IEnumerable<WebApp.Models.PricingPlan>

@{
    ViewBag.Title = "List of Pricing Plans";
}

@foreach (var plan in Model)
{
    <h3>@plan.Type.Name.ToUpper() PRICING PLAN</h3>

    <p>Hourly Pricing: @plan.HourlyPricing</p>
    <p>Daily Pricing: @plan.DailyPricing</p>
    <p>Minimum Hours: @plan.MinimumHours</p>
    <a class="btn btn-primary"
       asp-controller="PricingPlan"
       asp-action="EditPricingPlan"
       asp-route-id="@plan.Id">
        Edit
    </a>
    <br />
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SpotListing" asp-action="Total">All spots</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subscription" asp-action="ListAll">all subscriptions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PricingPlan" asp-action="PricingPlanList">Pricing Plans</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Log" asp-action="ListAll">Logs List</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/SpotListing/Total.cshtml
@model ParkingSpots

@{
	ViewBag.Title = "All Parking Spots";
}

<div class="card text-white bg-primary">
  <div class="card-header">Number of Available Spots </div>
  <div class="card-body">
    <h5 class="card-title">Total Spots: @Model.TotalSpots</h5>
    <h5 class="card-title">Reserved Spots: @Model.ReservedSpots</h5>
    <h5 class="card-title">Regular Spots: @Model.RegularSpots</h5>
  </div>
</div>

<form asp-controller="SpotListing" asp-action="Total" method="post">
    @Html.HiddenFor(model => model.ReservedSpots)
    @Html.HiddenFor(model => model.RegularSpots)
    <label for="TotalSpots">Update Total Spots</label>
    <input type="text" id="TotalSpots" name="TotalSpots" class="form-control" required />
    <br />
    <button type="submit" class="btn btn-primary">Update</button>
</form>

WebApp/Views/Subscription/AddSubscription.cshtml
@model Subscription

<h2 class="mb-4">Add Subscription</h2>

<form asp-action="AddSubscription" method="post" class="col-6">
    <div class="form-group mb-3">
        <label asp-for="Code" class="control-label">Code:</label>
        <input asp-for="Code" type="text" class="form-control" />
    </div>

    <div class="form-group mb-3">
        <label asp-for="Price" class="control-label">Price:</label>
        <textarea asp-for="Price" class="form-control"></textarea>
    </div>

    <div class="form-group mb-3">
        <label asp-for="DiscountValue" class="control-label">DiscountValue:</label>
        <input asp-for="DiscountValue" class="form-control" />
    </div>

    <div class="form-group mb-3">
        <label asp-for="StartDate" class="control-label">StartDate:</label>
        <input asp-for="StartDate" type="date" class="form-control" />
    </div>

    <div class="form-group mb-3">
        <label asp-for="EndDate" class="control-label">EndDate:</label>
        <input asp-for="EndDate" type="date" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Add Subscription</button>
</form>

WebApp/Views/Subscription/SubscriptionDetails.cshtml
@model Subscription

<div>
    @Model.Code
    @Model.Price
    @Model.DiscountValue
    @Model.StartDate
    @Model.EndDate
</div>

WebApp/Views/Subscription/SubscriptionsList.cshtml
@model IEnumerable<Subscription>

<div class="container col-12">
    <a class="nav-link text-dark" asp-area="" asp-controller="Subscription" asp-action="AddSubscription">add subscriptions</a>
    <h3 class="mt-4">List of Subscriptions</h3>
    <div class="row">
        @foreach (var subscription in Model)
        {
            <div class="col-4">
                <p>@subscription.Code</p>
                <p>@subscription.Price</p>
                <p>@subscription.DiscountValue</p>
                <p>@subscription.StartDate</p>
                <p>@subscription.EndDate</p>
                <a class="btn btn-primary"
                   asp-controller="Subscription"
                   asp-action="ViewSubscriptionDetails"
                   asp-route-id="@subscription.Id">
                    View Details
                </a>
                <a class="btn btn-primary"
                   asp-controller="Subscription"
                   asp-action="DeleteSubscription"
                   asp-route-id="@subscription.Id">
                    Delete
                </a>
            </div>
        }
    </div>
</div>